// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Case_2___Zealand_Lokale_Booking.Models;

public partial class BookngServiceContext : DbContext
{
    public BookngServiceContext()
    {
    }

    public BookngServiceContext(DbContextOptions<BookngServiceContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Booking> Bookings { get; set; }

    public virtual DbSet<Dag> Dags { get; set; }

    public virtual DbSet<Lokale> Lokales { get; set; }

    public virtual DbSet<Lokation> Lokations { get; set; }

    public virtual DbSet<LokationsAdresse> LokationsAdresses { get; set; }

    public virtual DbSet<Tid> Tids { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer("Data Source=DESKTOP-RTVVT6T;Initial Catalog=BookngService; Trust Server Certificate=True; User ID=sa;Password=Kusse505 ");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Booking>(entity =>
        {
            entity.HasKey(e => e.BookingId).HasName("PK__Booking__73951ACD4D3DC5F1");

            entity.HasOne(d => d.Dag).WithMany(p => p.Bookings)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Booking_Dag");

            entity.HasOne(d => d.Lokale).WithMany(p => p.Bookings)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Booking_Lokale");

            entity.HasOne(d => d.Lokation).WithMany(p => p.Bookings)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Booking_Lokation");

            entity.HasOne(d => d.Tid).WithMany(p => p.Bookings)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Booking_Tid");
        });

        modelBuilder.Entity<Dag>(entity =>
        {
            entity.HasKey(e => e.DagId).HasName("PK__Dag__A4B47848465F314F");
        });

        modelBuilder.Entity<Lokale>(entity =>
        {
            entity.HasKey(e => e.LokaleId).HasName("PK__Lokale__1C77899257B78F90");

            entity.HasOne(d => d.Lokations).WithMany(p => p.Lokales)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Lokale_Lokation");
        });

        modelBuilder.Entity<Lokation>(entity =>
        {
            entity.HasKey(e => e.LokationId).HasName("PK__Lokation__C799CC0A3A00E8E7");

            entity.HasOne(d => d.AdresseNavigation).WithMany(p => p.Lokations)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Lokation_LokationsAdresse");
        });

        modelBuilder.Entity<LokationsAdresse>(entity =>
        {
            entity.HasKey(e => e.Adresse).HasName("PK__Lokation__DA749F1A8464F474");
        });

        modelBuilder.Entity<Tid>(entity =>
        {
            entity.HasKey(e => e.TidId).HasName("PK__Tid__3898884937410605");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}