// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Case_2___Zealand_Lokale_Booking.Models;

[Table("Booking")]
public partial class Booking
{
    [Key]
    [Column("BookingID")]
    public int BookingId { get; set; }

    [Column("LokationID")]
    public int LokationId { get; set; }

    [Column("LokaleID")]
    public int LokaleId { get; set; }

    [Column("DagID")]
    public int DagId { get; set; }

    [Column("TidID")]
    public int TidId { get; set; }

    [Column("BrugerID")]
    public int? BrugerId { get; set; }

    [ForeignKey("BrugerId")]
    [InverseProperty("Bookings")]
    public virtual Brugere Bruger { get; set; }

    [ForeignKey("DagId")]
    [InverseProperty("Bookings")]
    public virtual Dag Dag { get; set; }

    [ForeignKey("LokaleId")]
    [InverseProperty("Bookings")]
    public virtual Lokale Lokale { get; set; }

    [ForeignKey("LokationId")]
    [InverseProperty("Bookings")]
    public virtual Lokation Lokation { get; set; }

    [ForeignKey("TidId")]
    [InverseProperty("Bookings")]
    public virtual Tid Tid { get; set; }
}