// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Case_2___Zealand_Lokale_Booking.Models;

[Table("Brugere")]
public partial class Brugere
{
    [Key]
    [Column("BrugerID")]
    public int BrugerId { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string BrugerNavn { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Kodeord { get; set; }

    [InverseProperty("Bruger")]
    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();



}