// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Case_2___Zealand_Lokale_Booking.Models;

[Table("Dag")]
public partial class Dag
{
    [Key]
    [Column("DagID")]
    public int DagId { get; set; }

    [Required]
    [StringLength(150)]
    [Unicode(false)]
    public string ValgteDag { get; set; }

    [InverseProperty("Dag")]
    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();
}