// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Case_2___Zealand_Lokale_Booking.Models;

[Table("Lokale")]
public partial class Lokale
{
    [Key]
    [Column("LokaleID")]
    public int LokaleId { get; set; }

    [Column("LokationsID")]
    public int LokationsId { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string LokaleNavn { get; set; }

    [Required]
    [StringLength(150)]
    [Unicode(false)]
    public string LokaleType { get; set; }

    [InverseProperty("Lokale")]
    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    [ForeignKey("LokationsId")]
    [InverseProperty("Lokales")]
    public virtual Lokation Lokations { get; set; }



    [NotMapped]
    public string LokaleNavnOgType { get { return $"{LokaleNavn} ({LokaleType})"; } }


}