// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Case_2___Zealand_Lokale_Booking.Models;

[Table("LokationsAdresse")]
public partial class LokationsAdresse
{
    [Key]
    [StringLength(250)]
    [Unicode(false)]
    public string Adresse { get; set; }

    public int PostNr { get; set; }

    [Required]
    [StringLength(150)]
    [Unicode(false)]
    public string ByNavn { get; set; }

    [InverseProperty("AdresseNavigation")]
    public virtual ICollection<Lokation> Lokations { get; set; } = new List<Lokation>();
}