// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Case_2___Zealand_Lokale_Booking.Models;

[Table("Lokation")]
public partial class Lokation
{
    [Key]
    [Column("LokationID")]
    public int LokationId { get; set; }

    [Required]
    [StringLength(250)]
    [Unicode(false)]
    public string Adresse { get; set; }

    [ForeignKey("Adresse")]
    [InverseProperty("Lokations")]
    public virtual LokationsAdresse AdresseNavigation { get; set; }

    [InverseProperty("Lokation")]
    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    [InverseProperty("Lokations")]
    public virtual ICollection<Lokale> Lokales { get; set; } = new List<Lokale>();


    public string ByNavn { get { return AdresseNavigation?.ByNavn; } }
}