// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Case_2___Zealand_Lokale_Booking.Models;

[Table("Tid")]
public partial class Tid
{
    [Key]
    [Column("TidID")]
    public int TidId { get; set; }

    [Required]
    [StringLength(150)]
    [Unicode(false)]
    public string ValgteTid { get; set; }

    [InverseProperty("Tid")]
    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();
}